// Package resources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for CapabilityMethods.
const (
	DELETE CapabilityMethods = "DELETE"
	GET    CapabilityMethods = "GET"
	PATCH  CapabilityMethods = "PATCH"
	POST   CapabilityMethods = "POST"
	PUT    CapabilityMethods = "PUT"
)

// Defines values for GroupEntitlementsPatchItemOp.
const (
	GroupEntitlementsPatchItemOpAdd    GroupEntitlementsPatchItemOp = "add"
	GroupEntitlementsPatchItemOpRemove GroupEntitlementsPatchItemOp = "remove"
)

// Defines values for GroupIdentitiesPatchItemOp.
const (
	GroupIdentitiesPatchItemOpAdd    GroupIdentitiesPatchItemOp = "add"
	GroupIdentitiesPatchItemOpRemove GroupIdentitiesPatchItemOp = "remove"
)

// Defines values for GroupRolesPatchItemOp.
const (
	GroupRolesPatchItemOpAdd    GroupRolesPatchItemOp = "add"
	GroupRolesPatchItemOpRemove GroupRolesPatchItemOp = "remove"
)

// Defines values for IdentityEntitlementsPatchItemOp.
const (
	IdentityEntitlementsPatchItemOpAdd    IdentityEntitlementsPatchItemOp = "add"
	IdentityEntitlementsPatchItemOpRemove IdentityEntitlementsPatchItemOp = "remove"
)

// Defines values for IdentityGroupsPatchItemOp.
const (
	IdentityGroupsPatchItemOpAdd    IdentityGroupsPatchItemOp = "add"
	IdentityGroupsPatchItemOpRemove IdentityGroupsPatchItemOp = "remove"
)

// Defines values for IdentityProviderSyncMode.
const (
	Import IdentityProviderSyncMode = "import"
)

// Defines values for IdentityRolesPatchItemOp.
const (
	IdentityRolesPatchItemOpAdd    IdentityRolesPatchItemOp = "add"
	IdentityRolesPatchItemOpRemove IdentityRolesPatchItemOp = "remove"
)

// Defines values for RoleEntitlementsPatchItemOp.
const (
	Add    RoleEntitlementsPatchItemOp = "add"
	Remove RoleEntitlementsPatchItemOp = "remove"
)

// AvailableIdentityProvider defines model for AvailableIdentityProvider.
type AvailableIdentityProvider struct {
	Id   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

// AvailableIdentityProviders defines model for AvailableIdentityProviders.
type AvailableIdentityProviders struct {
	Data []AvailableIdentityProvider `json:"data"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Data []Capability `json:"data"`
}

// Capability defines model for Capability.
type Capability struct {
	Endpoint string              `json:"endpoint"`
	Methods  []CapabilityMethods `json:"methods"`
}

// CapabilityMethods defines model for Capability.Methods.
type CapabilityMethods string

// EntitlementSchema defines model for EntitlementSchema.
type EntitlementSchema struct {
	Entitlement  string `json:"entitlement" validate:"required"`
	EntityType   string `json:"entity_type" validate:"required"`
	ReceiverType string `json:"receiver_type" validate:"required"`
}

// Entity defines model for Entity.
type Entity struct {
	Id   string `json:"id" validate:"required"`
	Name string `json:"name" validate:"required"`
	Type string `json:"type" validate:"required"`
}

// EntityEntitlement defines model for EntityEntitlement.
type EntityEntitlement struct {
	Entitlement string `json:"entitlement" validate:"required"`
	EntityId    string `json:"entity_id" validate:"required"`
	EntityType  string `json:"entity_type" validate:"required"`
}

// EntityEntitlementItem defines model for EntityEntitlementItem.
type EntityEntitlementItem struct {
	Entitlement EntityEntitlement `json:"entitlement"`
}

// GetAvailableIdentityProvidersResponse defines model for GetAvailableIdentityProvidersResponse.
type GetAvailableIdentityProvidersResponse struct {
	Links   ResponseLinks               `json:"_links"`
	Meta    ResponseMeta                `json:"_meta"`
	Data    []AvailableIdentityProvider `json:"data"`
	Message string                      `json:"message"`
	Status  int                         `json:"status"`
}

// GetCapabilitiesResponse defines model for GetCapabilitiesResponse.
type GetCapabilitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Capability  `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetEntitlementsResponse defines model for GetEntitlementsResponse.
type GetEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntitlementSchema `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupEntitlementsResponse defines model for GetGroupEntitlementsResponse.
type GetGroupEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupIdentitiesResponse defines model for GetGroupIdentitiesResponse.
type GetGroupIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupRolesResponse defines model for GetGroupRolesResponse.
type GetGroupRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupsResponse defines model for GetGroupsResponse.
type GetGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentitiesResponse defines model for GetIdentitiesResponse.
type GetIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityEntitlementsResponse defines model for GetIdentityEntitlementsResponse.
type GetIdentityEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetIdentityGroupsResponse defines model for GetIdentityGroupsResponse.
type GetIdentityGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityProvidersResponse defines model for GetIdentityProvidersResponse.
type GetIdentityProvidersResponse struct {
	Links   ResponseLinks      `json:"_links"`
	Meta    ResponseMeta       `json:"_meta"`
	Data    []IdentityProvider `json:"data"`
	Message string             `json:"message"`
	Status  int                `json:"status"`
}

// GetIdentityRolesResponse defines model for GetIdentityRolesResponse.
type GetIdentityRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetResourcesResponse defines model for GetResourcesResponse.
type GetResourcesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Resource    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetRoleEntitlementsResponse defines model for GetRoleEntitlementsResponse.
type GetRoleEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetRolesResponse defines model for GetRolesResponse.
type GetRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// Group defines model for Group.
type Group struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name" validate:"required"`
}

// GroupEntitlementsPatchItem defines model for GroupEntitlementsPatchItem.
type GroupEntitlementsPatchItem struct {
	Entitlement EntityEntitlement            `json:"entitlement"`
	Op          GroupEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupEntitlementsPatchItemOp defines model for GroupEntitlementsPatchItem.Op.
type GroupEntitlementsPatchItemOp string

// GroupEntitlementsPatchRequestBody defines model for GroupEntitlementsPatchRequestBody.
type GroupEntitlementsPatchRequestBody struct {
	Patches []GroupEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// GroupIdentitiesPatchItem defines model for GroupIdentitiesPatchItem.
type GroupIdentitiesPatchItem struct {
	Identity string                     `json:"identity" validate:"required"`
	Op       GroupIdentitiesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupIdentitiesPatchItemOp defines model for GroupIdentitiesPatchItem.Op.
type GroupIdentitiesPatchItemOp string

// GroupIdentitiesPatchRequestBody defines model for GroupIdentitiesPatchRequestBody.
type GroupIdentitiesPatchRequestBody struct {
	Patches []GroupIdentitiesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// GroupRolesPatchItem defines model for GroupRolesPatchItem.
type GroupRolesPatchItem struct {
	Op   GroupRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                `json:"role" validate:"required"`
}

// GroupRolesPatchItemOp defines model for GroupRolesPatchItem.Op.
type GroupRolesPatchItemOp string

// GroupRolesPatchRequestBody defines model for GroupRolesPatchRequestBody.
type GroupRolesPatchRequestBody struct {
	Patches []GroupRolesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Groups defines model for Groups.
type Groups struct {
	Data []Group `json:"data"`
}

// Identities defines model for Identities.
type Identities struct {
	Data []Identity `json:"data"`
}

// Identity defines model for Identity.
type Identity struct {
	AddedBy     string  `json:"addedBy" validate:"required"`
	Certificate *string `json:"certificate,omitempty"`
	Email       string  `json:"email" validate:"required"`
	FirstName   *string `json:"firstName,omitempty"`
	Groups      *int    `json:"groups,omitempty"`
	Id          *string `json:"id,omitempty"`
	Joined      *string `json:"joined,omitempty"`
	LastLogin   *string `json:"lastLogin,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Permissions *int    `json:"permissions,omitempty"`
	Roles       *int    `json:"roles,omitempty"`
	Source      string  `json:"source" validate:"required"`
}

// IdentityEntitlementsPatchItem defines model for IdentityEntitlementsPatchItem.
type IdentityEntitlementsPatchItem struct {
	Entitlement EntityEntitlement               `json:"entitlement"`
	Op          IdentityEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityEntitlementsPatchItemOp defines model for IdentityEntitlementsPatchItem.Op.
type IdentityEntitlementsPatchItemOp string

// IdentityEntitlementsPatchRequestBody defines model for IdentityEntitlementsPatchRequestBody.
type IdentityEntitlementsPatchRequestBody struct {
	Patches []IdentityEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// IdentityGroupsPatchItem defines model for IdentityGroupsPatchItem.
type IdentityGroupsPatchItem struct {
	Group string                    `json:"group" validate:"required"`
	Op    IdentityGroupsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityGroupsPatchItemOp defines model for IdentityGroupsPatchItem.Op.
type IdentityGroupsPatchItemOp string

// IdentityGroupsPatchRequestBody defines model for IdentityGroupsPatchRequestBody.
type IdentityGroupsPatchRequestBody struct {
	Patches []IdentityGroupsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// IdentityProvider defines model for IdentityProvider.
type IdentityProvider struct {
	AcceptsPromptNone   *bool                     `json:"acceptsPromptNone,omitempty"`
	AccountLinkingOnly  *bool                     `json:"accountLinkingOnly,omitempty"`
	ClientID            *string                   `json:"clientID,omitempty"`
	ClientSecret        *string                   `json:"clientSecret,omitempty"`
	DisableIdentityInfo *bool                     `json:"disableIdentityInfo,omitempty"`
	Enabled             *bool                     `json:"enabled,omitempty"`
	Id                  *string                   `json:"id,omitempty"`
	IdentityCount       *int                      `json:"identityCount,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	RedirectUrl         *string                   `json:"redirectUrl,omitempty"`
	StoreTokens         *bool                     `json:"storeTokens,omitempty"`
	StoreTokensReadable *bool                     `json:"storeTokensReadable,omitempty"`
	SyncMode            *IdentityProviderSyncMode `json:"syncMode,omitempty" validate:"omitempty,oneof=import"`
	TrustEmail          *bool                     `json:"trustEmail,omitempty"`
}

// IdentityProviderSyncMode defines model for IdentityProvider.SyncMode.
type IdentityProviderSyncMode string

// IdentityProviders defines model for IdentityProviders.
type IdentityProviders struct {
	Data []IdentityProvider `json:"data"`
}

// IdentityRolesPatchItem defines model for IdentityRolesPatchItem.
type IdentityRolesPatchItem struct {
	Op   IdentityRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                   `json:"role" validate:"required"`
}

// IdentityRolesPatchItemOp defines model for IdentityRolesPatchItem.Op.
type IdentityRolesPatchItemOp string

// IdentityRolesPatchRequestBody defines model for IdentityRolesPatchRequestBody.
type IdentityRolesPatchRequestBody struct {
	Patches []IdentityRolesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Resource defines model for Resource.
type Resource struct {
	Entity Entity  `json:"entity"`
	Parent *Entity `json:"parent,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	Data []Resource `json:"data"`
}

// Response defines model for Response.
type Response struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// ResponseLinks defines model for ResponseLinks.
type ResponseLinks struct {
	Next ResponseLinksNext `json:"next"`
}

// ResponseLinksNext defines model for ResponseLinksNext.
type ResponseLinksNext struct {
	Href string `json:"href"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Page      *int    `json:"page,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	Size      int     `json:"size"`
	Total     *int    `json:"total,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Entitlements *[]RoleEntitlement `json:"entitlements,omitempty" validate:"omitempty,dive"`
	Id           *string            `json:"id,omitempty"`
	Name         string             `json:"name" validate:"required"`
}

// RoleEntitlement defines model for RoleEntitlement.
type RoleEntitlement struct {
	Entitlement *string `json:"entitlement,omitempty"`
	Entity      *Entity `json:"entity,omitempty"`
	Resource    *string `json:"resource,omitempty"`
}

// RoleEntitlementsPatchItem defines model for RoleEntitlementsPatchItem.
type RoleEntitlementsPatchItem struct {
	Entitlement EntityEntitlement           `json:"entitlement"`
	Op          RoleEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// RoleEntitlementsPatchItemOp defines model for RoleEntitlementsPatchItem.Op.
type RoleEntitlementsPatchItemOp string

// RoleEntitlementsPatchRequestBody defines model for RoleEntitlementsPatchRequestBody.
type RoleEntitlementsPatchRequestBody struct {
	Patches []RoleEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Roles defines model for Roles.
type Roles struct {
	Data []Role `json:"data"`
}

// FilterParam defines model for FilterParam.
type FilterParam = string

// PaginationNextToken defines model for PaginationNextToken.
type PaginationNextToken = string

// PaginationNextTokenHeader defines model for PaginationNextTokenHeader.
type PaginationNextTokenHeader = string

// PaginationPage defines model for PaginationPage.
type PaginationPage = int

// PaginationSize defines model for PaginationSize.
type PaginationSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Response

// NotFound defines model for NotFound.
type NotFound = Response

// Unauthorized defines model for Unauthorized.
type Unauthorized = Response

// Default defines model for default.
type Default = Response

// GetIdentityProvidersParams defines parameters for GetIdentityProviders.
type GetIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetAvailableIdentityProvidersParams defines parameters for GetAvailableIdentityProviders.
type GetAvailableIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetEntitlementsParams defines parameters for GetEntitlements.
type GetEntitlementsParams struct {
	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetGroupsParams defines parameters for GetGroups.
type GetGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemEntitlementsParams defines parameters for GetGroupsItemEntitlements.
type GetGroupsItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemIdentitiesParams defines parameters for GetGroupsItemIdentities.
type GetGroupsItemIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemRolesParams defines parameters for GetGroupsItemRoles.
type GetGroupsItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesParams defines parameters for GetIdentities.
type GetIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemEntitlementsParams defines parameters for GetIdentitiesItemEntitlements.
type GetIdentitiesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemGroupsParams defines parameters for GetIdentitiesItemGroups.
type GetIdentitiesItemGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemRolesParams defines parameters for GetIdentitiesItemRoles.
type GetIdentitiesItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetResourcesParams defines parameters for GetResources.
type GetResourcesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken  *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	EntityType *string              `form:"entityType,omitempty" json:"entityType,omitempty"`
	EntityName *string              `form:"entityName,omitempty" json:"entityName,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesItemEntitlementsParams defines parameters for GetRolesItemEntitlements.
type GetRolesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// PostIdentityProvidersJSONRequestBody defines body for PostIdentityProviders for application/json ContentType.
type PostIdentityProvidersJSONRequestBody = IdentityProvider

// PutIdentityProvidersItemJSONRequestBody defines body for PutIdentityProvidersItem for application/json ContentType.
type PutIdentityProvidersItemJSONRequestBody = IdentityProvider

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody = Group

// PutGroupsItemJSONRequestBody defines body for PutGroupsItem for application/json ContentType.
type PutGroupsItemJSONRequestBody = Group

// PatchGroupsItemEntitlementsJSONRequestBody defines body for PatchGroupsItemEntitlements for application/json ContentType.
type PatchGroupsItemEntitlementsJSONRequestBody = GroupEntitlementsPatchRequestBody

// PatchGroupsItemIdentitiesJSONRequestBody defines body for PatchGroupsItemIdentities for application/json ContentType.
type PatchGroupsItemIdentitiesJSONRequestBody = GroupIdentitiesPatchRequestBody

// PatchGroupsItemRolesJSONRequestBody defines body for PatchGroupsItemRoles for application/json ContentType.
type PatchGroupsItemRolesJSONRequestBody = GroupRolesPatchRequestBody

// PostIdentitiesJSONRequestBody defines body for PostIdentities for application/json ContentType.
type PostIdentitiesJSONRequestBody = Identity

// PutIdentitiesItemJSONRequestBody defines body for PutIdentitiesItem for application/json ContentType.
type PutIdentitiesItemJSONRequestBody = Identity

// PatchIdentitiesItemEntitlementsJSONRequestBody defines body for PatchIdentitiesItemEntitlements for application/json ContentType.
type PatchIdentitiesItemEntitlementsJSONRequestBody = IdentityEntitlementsPatchRequestBody

// PatchIdentitiesItemGroupsJSONRequestBody defines body for PatchIdentitiesItemGroups for application/json ContentType.
type PatchIdentitiesItemGroupsJSONRequestBody = IdentityGroupsPatchRequestBody

// PatchIdentitiesItemRolesJSONRequestBody defines body for PatchIdentitiesItemRoles for application/json ContentType.
type PatchIdentitiesItemRolesJSONRequestBody = IdentityRolesPatchRequestBody

// PostRolesJSONRequestBody defines body for PostRoles for application/json ContentType.
type PostRolesJSONRequestBody = Role

// PutRolesItemJSONRequestBody defines body for PutRolesItem for application/json ContentType.
type PutRolesItemJSONRequestBody = Role

// PatchRolesItemEntitlementsJSONRequestBody defines body for PatchRolesItemEntitlements for application/json ContentType.
type PatchRolesItemEntitlementsJSONRequestBody = RoleEntitlementsPatchRequestBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd3XPbNpD/VzC4e8rQlnLNvWimM+cmaeJeanscZ+4h9XQgciWhJgEWAG2rGf3vNwD4",
	"TZCivhw14ktiiSCwWPz2A4td6Bv2eRRzBkxJPPmGYyJIBAqE+fQrDRWIG/2d/hiA9AWNFeUMT/AFkkpQ",
	"NkeKo5lpiATIJFQSTZfYw1Q3+jsBoT8wEgGeYNsOe1j6C4iI7lQtY/3E9oVXKw/fkDllRI9yBc/qjj8A",
	"a45+twDkc6YoS0xTpHQ7TYsAJSg8AlILQAyeFZKgEJ9l1LWQxvKxNqbuI5AAxCFoXNiecyL1kGc3ZA5n",
	"m5GqX3HTJ8DnIkB8NtMUWNISwfKlnAketXAs1p2WKYgoo1ES4clrL6OGMgVzEDVyPtN/WshhSTQFYTmh",
	"CZMlkmKLsJgzCS0kSd1xhSTynJI0HnvdBK48nPVuwP8LCW7h7wSk0p/0OgIzf5I4DqlvJjL6S3IDTngm",
	"URyaSf0ZUvZgetALq/9fCJjhCTZM+DMCRayk6SUZe5Zm/YfiioR4Ml55OCC60dd7D0cgpWmp6UEiJcjD",
	"UhGVSDx5M9btiwn/px3rP0aFXI/sUzm6zZhnJltlvu49m+7Kw1dc/coTFhzH1K+4QjNDTnnib/Yy8aLv",
	"lYe/MJKoBRf0HziSqVcoKs/+9V5mX+nePJ2RJFTHMnd4jsFXECAQgovS/P97T7BvDLHKuzUTungkNCTT",
	"EC4DYIqq5Y3gjzTV9rHgMQhFrb6ggUMLZ5rJpZ61MFOhgfZVv3yf6yQ+/Qt8I4atw8vm+JaD3zBVEMl1",
	"PGmf1yongwhBlg1KzTAuWt+SmExpSDN6UoBIPPmaEff1GwYWxJxqWOERtWPr9nrZ1YIHujX+8P4O36/u",
	"V/feLlPM6VnuYU7LJr+LmThWPZ9NiVhg2vTY6Xn45vqz+e+L/vfd+0/v797rjxd3bz+WSCl67JxATksx",
	"sms67zW7Q4iAqc+56NRnlTepSPlXTIKIao/jSVDtwzVo9PDzGScxPfN5AHNgZ/CsBDlTZG46fiQhDYjS",
	"L+SU62lY+P1p+6oMqBWQ4GFoHKCIBxDubVABPtBHEK5hU1Rqr2IueBLvadDGihXTrtPjVVahdSGXDSnT",
	"KggnCQ1KHjfnOO+gxNGmcLn015bsdeu8LTvLlmj/a5Ayu2BXO6vfV8WiU2b2KRZ7XJSaoB0a0sUE+sK5",
	"xONLBdFaPncp/+aqOantoOkDqHbrm7sU2jkKw+uZEb9+Toi3pWWWeHVv6Spb2gNSUjHo2dgllu469g62",
	"vWnItjTx6aw+aEV/RFOrInf3qV3mntYB8VIMUh38locHHdf0Xx3ykMPZAfLxvhdrM/XwY6I2m913Ws0X",
	"0fTtCj578rKScwuSJ8I/7IjZGMWoPIQfE8MvuXpmo7JbSGIfLmCrF90wsDdE+YvMzevHGLeX2Fx0Hpd3",
	"2yQIzAYr4o+wj62cxxnw2c8kCFDaaYMLPG4DhZMLadj1Fx44ogyxbgGyN4g7GL0yAfBL28vrGrS3YMRc",
	"/Tz2AuriQEZ1KxQKg1YBQh2+kO9z97IF+u7IKMUWnCBxc2f/AHGx/5jgYVRbBzJefiE9LHh4IK1peu5G",
	"RMGQ/YOhxuxjwsGuYW5rF7cO/5bc7t3oyBy6nUlxrDkJAgh+qQcDMX+o9LSb4vT1cDPqm0cOjwIiQsO9",
	"qekZFVJduc9N0qCsLD3Kj3C9NofnL04ZuB+FRKpPfE5Z69NWQmIQEZWSctZCjTAOmvOR9YLrawbPCgQj",
	"oTndTv88TPTZrFdOhpeDqAt6J+++tTJirzq5m91Hop2r+/MOSz3PdiY/hgNnp9Nqqx1sOQg26mw/MlS0",
	"H5IT34dYyRvBo1hdcVbWrFPOQyBMd0R8nydMfaLsgbL5NQuX7nZ+SLUieefUz/bhZ/AFuA9pAyrLgfZL",
	"NuPuYYDpdoH7YYvNyVz9t3oibiPA2iyLgIAK8NUXETqfS8UFmAww6aap1OAWSKCpb2m4ZP7vPICyWNEo",
	"5kLtIlA80miO1TKVqLRHc5onEqne19yFnKBVD1DtyxfbPeOhEqYbdistPDmIAjzOPUsW3Ww5ulz2i0Aa",
	"35KI3qec7qPNZSeFuwpRPtOthaccGK0SUqST9QmTfjKNy3lmfd76XbddlZLNnFrW5pp9cyWzlueYNsxI",
	"8LIZFN13MeBTNtsqF7JUut48uNIvNAKy+su1o1+lY1UpsEl86zLXTKuuEX7P0v9qgl/heskq6id50ndz",
	"UdLU4eZ7aTLh+tXSPTgJTlVma9JBfzVVO9RoSMk2pjRVR94RRfXr09wsMybPSemvFkVJwTZhuY6+09y1",
	"OpmwV6PczuZjsctZIGYXi6e1w5bWzkhturvwOVPEt8mV1g3GYfIA508gQ1ieLXgYwvJ/fMI4oz4Jz31T",
	"f5Fm831KHgD9n2350bTEjZTmuwWgGQ9D/kTZHMkYfBu5o5whnqiQMpCm7uTi5hJlxKMZF+bLXz9cIJPp",
	"SaUS9qWZMJngAVIcmbAU8RV6omqBCEPXMTD9DmVSEeYDUgvBk/kCERQLHiS+knqgc3S3oBJRqd+BRx4+",
	"NokjEgmYhTYbmzJDziMIqZ/ZupDzPxj2sAEanuC3GY9yIi6qhN9YAtBbHsVEUZvIq6nBHk47xhM8Ph+f",
	"vx5jE10ARmKKJ/in89fnY6xtkVoYZIxIohZaW1laTWTD7irrzKcSZdm4KKRSSUTCEKU7SM0Tu4mxU9Fo",
	"NB1eBnjizD8wRBQ1WS3aqmgyqlXZtB0iO98wZUIbvVFUaG33Wlo6tbqvFd/813jcowahX/5/Z1qHoybg",
	"+n81GN5YClwd55SOSjVC5pXX61+pV1y8Gb9Z/1JejlMt0eh+KWtoShqSKCJiqVUIlQr5nM3oPNGCXwV2",
	"CaBa0owq/opr4NdWJebSAf+3Wb+IIAZPbZ2fN6B/w6UT+6Jqp/aCh2YAoKrGlUhgdUA8usc/JQxuAJNW",
	"CK68ulIexeUIUQ/1LBc8CYOsvJAYdY34LBtfogfGn0y9pjZFcikVRJ6xlOmhDbp+UMRDHzifh+ChD1R9",
	"TKYIlH/+RzIe/+RPBRqZv+AP9urV3fW761evJugMfTZ2b2m6TUfXHoPbJHQkBA+2YQ+2oUeW98kJ6K0B",
	"pXUTM6mQSRxzYXyzlFE9jYVDUr/RYGWlMwTlKAW+NZsc7Su2qIbcgpmvm/bknem4saJmU+KG02kt78bs",
	"7XAFnJr2AyhEkKRsHkJ/N8DlqnWs2WCO9wKHvmvV5Q5W7ZCpzdebp2LrSgNcd7K6bi+493CcOHD1JQ6I",
	"2kUz3CQdEBuczR8P3VsgptOU+bU65x6O5hMNQzQFlEgI0NT6feWoSqAlJ6IM0NOC+gv05RJBGkvLnNQp",
	"5DGEIsISkTimbH6OLsIQkcyPycctv6ytOARoAdrpDjmb2wiOpqR4Ma0ddurlSjXYYT0yZ31bC27Xui0F",
	"M6h22TVTs0WgNjRVWvDK2trlrsf/W5YbUH3K+V0lxre3GMic/QWg3z5fX6FUMqQFpKlxdjK/HF3d2Osv",
	"3+JzaGfaWclxkga1isGCK4gyu/YzLiKiyuirQK2JvpEgT50IVPCsRnFI6DrsCfLUG3q35KmGvjX4Kaio",
	"Iqdu4QdMFJgg0qyJZt0aQBTZr+1udxgi28y5oGli9WnEDryj0o61asbT3GhU0JkhPYV1R2RZgPHiTLzQ",
	"tHYHkXN0H8KZT8sJXtaDLw16UjFi54I38FLoxN5BpTb42JiRBdAQKKoEijoWoE/8p4XhuUY8dIjnREXI",
	"vQYulfvS0ZtWDZ7UETEo8R8h9tJfgffbb5tDbJsjX3WktYdtekMLItdonJ021cNRWpt/O4QAlhsh9KX0",
	"MVH+wnGLcxAgLtKsQkTcJPPRTPCoQ23rvlsFazMlXtRDmtLWCxZYJ8QAMWfvBcvP4PkMTblNRiNBgAjL",
	"ciRRTiT28CMJE6gkN35tXnZY/lj+dEYqF5qlz5ZnNCg/SZmePtOfzghOi9ZMRqiW3d5DTluHnHYOOc2H",
	"zDJF71er3nelrr+hYtW8KfkEHeMtxWat9aOVivNWz1orkaKpFgHSy8m+LN+4Ohi8/Rg8xw1gJxvdbAXl",
	"MVm5EpGbmraKAB2vYStuzsn/NJaqYopcjaZ4V+PRcXdN/z3X6ZqSbmyutR/5lROdpsO06m81bPnEYDD2",
	"ZTCqF8OdrK1wofC4NkOawlwM843bWiORycvx2ofcDmSF4uY/s135VtH/1efTLeyBuxB8MAV9dhXt+HMa",
	"gp6bh+wEumjelYh5OnuF4zorHnYVXWjN8F+CfPvZ8YXRjnnaemf10Tae/WaZmN8rA/T04ONYdyduqrpz",
	"g+KEdkRV6g8oDOfJ9cKDtYvS51y5nf8VBfpSFQQnfsLcY0m/Q5lAh9ZPXBgZFP+PlPK/je7f4Ai6cbKX",
	"l8a1HT9XETccQR+q0n84hV72BulLKus+gZcSwUUQtFOTmwtnuiRrOIP+95xB97pmdziGXm4jN71t4Jo6",
	"A6NYbJuqSqESERRB+ivOPUzgSZUjvJDxO/U6gw3QeWy2r0JuJsRt1TwOu7dl/cNLWrz0SnD7f/NYuvp4",
	"pwPpNddxDzZkuSn+etuP7oNoI6D2/I9ISecMguyanQ1iOsO59N4tx4kfTffE5b/CaJhp9LIZw3l12+Xi",
	"g7XYwlrkwGs1FqJ8C3lnplJ2+lfcUZG/665Wz3s+mTNro2b+TkAsCz1jV+TO/hJ3AX7HlQHLGPJqdL2E",
	"aGbOuNF0ib3mFctdo5nfSeoeTbdHsYAZfe4/6IEtX/NXT0/+aoIWYcvEuZDeVJp75RxmnbeYpez3Uodc",
	"k++QazIkJLohmiPeILPn5QS6sTvFZDs/q98q2uvJX/aAsRjzZC8myBa7jpRcL67NJrGZImmyX1siiUHO",
	"kENi+N9gWFNK12eOuJmdqcJDJ4ycpuA4F8ChYl/8MoIWjZ3UwDAo7R/gIoJ+CrtfCkjmN1QO2E09w3r1",
	"MmR+HMKJHbI+lr1w+UJadx9XDrQoZxOdaxGmIdnj35PssfbXqYaw63JrmXEZOflE5nMQ5xn8e1xfLErX",
	"6pYv0b2OgV3cXJqfcfLSq4v97MJhc9fxjAsUwDSZzymbe2gq+JM0f+nXAip9/ghi6ZmfzGjI+GdL6W/S",
	"yNNOpqPX3aOtVwmX54mIRCS9wJVWuWx+/DHFPojHTJVWB4pD4sOCh9oiejgRIZ7ghVKxnIxGpWfnPo9G",
	"j6+N0Uz7b6hRVqyQuUNaP5zamHz5HmOtr9Kf+yqUeeWiY60mHOezJAzrV2anF0QXEcKix9pd2c0+L5DP",
	"wxB8+0Nk5YKeso3Jv1vfwTxLdUhfTj+vf1GkcZj0Pftx/WtQtTLl4Hf2bY+xSwcU2fj5V6v71f8HAAD/",
	"/8Kf5IyRoQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
