// Package resources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for CapabilityMethods.
const (
	DELETE CapabilityMethods = "DELETE"
	GET    CapabilityMethods = "GET"
	PATCH  CapabilityMethods = "PATCH"
	POST   CapabilityMethods = "POST"
	PUT    CapabilityMethods = "PUT"
)

// Defines values for GroupEntitlementsPatchItemOp.
const (
	GroupEntitlementsPatchItemOpAdd    GroupEntitlementsPatchItemOp = "add"
	GroupEntitlementsPatchItemOpRemove GroupEntitlementsPatchItemOp = "remove"
)

// Defines values for GroupIdentitiesPatchItemOp.
const (
	GroupIdentitiesPatchItemOpAdd    GroupIdentitiesPatchItemOp = "add"
	GroupIdentitiesPatchItemOpRemove GroupIdentitiesPatchItemOp = "remove"
)

// Defines values for GroupRolesPatchItemOp.
const (
	GroupRolesPatchItemOpAdd    GroupRolesPatchItemOp = "add"
	GroupRolesPatchItemOpRemove GroupRolesPatchItemOp = "remove"
)

// Defines values for IdentityEntitlementsPatchItemOp.
const (
	IdentityEntitlementsPatchItemOpAdd    IdentityEntitlementsPatchItemOp = "add"
	IdentityEntitlementsPatchItemOpRemove IdentityEntitlementsPatchItemOp = "remove"
)

// Defines values for IdentityGroupsPatchItemOp.
const (
	IdentityGroupsPatchItemOpAdd    IdentityGroupsPatchItemOp = "add"
	IdentityGroupsPatchItemOpRemove IdentityGroupsPatchItemOp = "remove"
)

// Defines values for IdentityProviderSyncMode.
const (
	Import IdentityProviderSyncMode = "import"
)

// Defines values for IdentityRolesPatchItemOp.
const (
	IdentityRolesPatchItemOpAdd    IdentityRolesPatchItemOp = "add"
	IdentityRolesPatchItemOpRemove IdentityRolesPatchItemOp = "remove"
)

// Defines values for RoleEntitlementsPatchItemOp.
const (
	Add    RoleEntitlementsPatchItemOp = "add"
	Remove RoleEntitlementsPatchItemOp = "remove"
)

// AvailableIdentityProvider defines model for AvailableIdentityProvider.
type AvailableIdentityProvider struct {
	Id   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

// AvailableIdentityProviders defines model for AvailableIdentityProviders.
type AvailableIdentityProviders struct {
	Data []AvailableIdentityProvider `json:"data"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Data []Capability `json:"data"`
}

// Capability defines model for Capability.
type Capability struct {
	Endpoint string              `json:"endpoint"`
	Methods  []CapabilityMethods `json:"methods"`
}

// CapabilityMethods defines model for Capability.Methods.
type CapabilityMethods string

// Entity defines model for Entity.
type Entity struct {
	Id   string `json:"id" validate:"required"`
	Type string `json:"type" validate:"required"`
}

// EntityEntitlement defines model for EntityEntitlement.
type EntityEntitlement struct {
	EntitlementType string `json:"entitlement_type" validate:"required"`
	EntityName      string `json:"entity_name" validate:"required"`
	EntityType      string `json:"entity_type" validate:"required"`
}

// EntityEntitlementItem defines model for EntityEntitlementItem.
type EntityEntitlementItem struct {
	Entitlement EntityEntitlement `json:"entitlement"`
}

// GetAvailableIdentityProvidersResponse defines model for GetAvailableIdentityProvidersResponse.
type GetAvailableIdentityProvidersResponse struct {
	Links   ResponseLinks               `json:"_links"`
	Meta    ResponseMeta                `json:"_meta"`
	Data    []AvailableIdentityProvider `json:"data"`
	Message string                      `json:"message"`
	Status  int                         `json:"status"`
}

// GetCapabilitiesResponse defines model for GetCapabilitiesResponse.
type GetCapabilitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Capability  `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetEntitlementsResponse defines model for GetEntitlementsResponse.
type GetEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupEntitlementsResponse defines model for GetGroupEntitlementsResponse.
type GetGroupEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupIdentitiesResponse defines model for GetGroupIdentitiesResponse.
type GetGroupIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupRolesResponse defines model for GetGroupRolesResponse.
type GetGroupRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupsResponse defines model for GetGroupsResponse.
type GetGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentitiesResponse defines model for GetIdentitiesResponse.
type GetIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityEntitlementsResponse defines model for GetIdentityEntitlementsResponse.
type GetIdentityEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetIdentityGroupsResponse defines model for GetIdentityGroupsResponse.
type GetIdentityGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityProvidersResponse defines model for GetIdentityProvidersResponse.
type GetIdentityProvidersResponse struct {
	Links   ResponseLinks      `json:"_links"`
	Meta    ResponseMeta       `json:"_meta"`
	Data    []IdentityProvider `json:"data"`
	Message string             `json:"message"`
	Status  int                `json:"status"`
}

// GetIdentityRolesResponse defines model for GetIdentityRolesResponse.
type GetIdentityRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetResourcesResponse defines model for GetResourcesResponse.
type GetResourcesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Resource    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetRoleEntitlementsResponse defines model for GetRoleEntitlementsResponse.
type GetRoleEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetRolesResponse defines model for GetRolesResponse.
type GetRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// Group defines model for Group.
type Group struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name" validate:"required"`
}

// GroupEntitlementsPatchItem defines model for GroupEntitlementsPatchItem.
type GroupEntitlementsPatchItem struct {
	Entitlement EntityEntitlement            `json:"entitlement"`
	Op          GroupEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupEntitlementsPatchItemOp defines model for GroupEntitlementsPatchItem.Op.
type GroupEntitlementsPatchItemOp string

// GroupEntitlementsPatchRequestBody defines model for GroupEntitlementsPatchRequestBody.
type GroupEntitlementsPatchRequestBody struct {
	Patches []GroupEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// GroupIdentitiesPatchItem defines model for GroupIdentitiesPatchItem.
type GroupIdentitiesPatchItem struct {
	Identity string                     `json:"identity" validate:"required"`
	Op       GroupIdentitiesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupIdentitiesPatchItemOp defines model for GroupIdentitiesPatchItem.Op.
type GroupIdentitiesPatchItemOp string

// GroupIdentitiesPatchRequestBody defines model for GroupIdentitiesPatchRequestBody.
type GroupIdentitiesPatchRequestBody struct {
	Patches []GroupIdentitiesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// GroupRolesPatchItem defines model for GroupRolesPatchItem.
type GroupRolesPatchItem struct {
	Op   GroupRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                `json:"role" validate:"required"`
}

// GroupRolesPatchItemOp defines model for GroupRolesPatchItem.Op.
type GroupRolesPatchItemOp string

// GroupRolesPatchRequestBody defines model for GroupRolesPatchRequestBody.
type GroupRolesPatchRequestBody struct {
	Patches []GroupRolesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Groups defines model for Groups.
type Groups struct {
	Data []Group `json:"data"`
}

// Identities defines model for Identities.
type Identities struct {
	Data []Identity `json:"data"`
}

// Identity defines model for Identity.
type Identity struct {
	AddedBy     string  `json:"addedBy" validate:"required"`
	Certificate *string `json:"certificate,omitempty"`
	Email       string  `json:"email" validate:"required"`
	FirstName   *string `json:"firstName,omitempty"`
	Groups      *int    `json:"groups,omitempty"`
	Id          *string `json:"id,omitempty"`
	Joined      *string `json:"joined,omitempty"`
	LastLogin   *string `json:"lastLogin,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Permissions *int    `json:"permissions,omitempty"`
	Roles       *int    `json:"roles,omitempty"`
	Source      string  `json:"source" validate:"required"`
}

// IdentityEntitlementsPatchItem defines model for IdentityEntitlementsPatchItem.
type IdentityEntitlementsPatchItem struct {
	Entitlement EntityEntitlement               `json:"entitlement"`
	Op          IdentityEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityEntitlementsPatchItemOp defines model for IdentityEntitlementsPatchItem.Op.
type IdentityEntitlementsPatchItemOp string

// IdentityEntitlementsPatchRequestBody defines model for IdentityEntitlementsPatchRequestBody.
type IdentityEntitlementsPatchRequestBody struct {
	Patches []IdentityEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// IdentityGroupsPatchItem defines model for IdentityGroupsPatchItem.
type IdentityGroupsPatchItem struct {
	Group string                    `json:"group" validate:"required"`
	Op    IdentityGroupsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityGroupsPatchItemOp defines model for IdentityGroupsPatchItem.Op.
type IdentityGroupsPatchItemOp string

// IdentityGroupsPatchRequestBody defines model for IdentityGroupsPatchRequestBody.
type IdentityGroupsPatchRequestBody struct {
	Patches []IdentityGroupsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// IdentityProvider defines model for IdentityProvider.
type IdentityProvider struct {
	AcceptsPromptNone   *bool                     `json:"acceptsPromptNone,omitempty"`
	AccountLinkingOnly  *bool                     `json:"accountLinkingOnly,omitempty"`
	ClientID            *string                   `json:"clientID,omitempty"`
	ClientSecret        *string                   `json:"clientSecret,omitempty"`
	DisableIdentityInfo *bool                     `json:"disableIdentityInfo,omitempty"`
	Enabled             *bool                     `json:"enabled,omitempty"`
	Id                  *string                   `json:"id,omitempty"`
	IdentityCount       *int                      `json:"identityCount,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	RedirectUrl         *string                   `json:"redirectUrl,omitempty"`
	StoreTokens         *bool                     `json:"storeTokens,omitempty"`
	StoreTokensReadable *bool                     `json:"storeTokensReadable,omitempty"`
	SyncMode            *IdentityProviderSyncMode `json:"syncMode,omitempty" validate:"omitempty,oneof=import"`
	TrustEmail          *bool                     `json:"trustEmail,omitempty"`
}

// IdentityProviderSyncMode defines model for IdentityProvider.SyncMode.
type IdentityProviderSyncMode string

// IdentityProviders defines model for IdentityProviders.
type IdentityProviders struct {
	Data []IdentityProvider `json:"data"`
}

// IdentityRolesPatchItem defines model for IdentityRolesPatchItem.
type IdentityRolesPatchItem struct {
	Op   IdentityRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                   `json:"role" validate:"required"`
}

// IdentityRolesPatchItemOp defines model for IdentityRolesPatchItem.Op.
type IdentityRolesPatchItemOp string

// IdentityRolesPatchRequestBody defines model for IdentityRolesPatchRequestBody.
type IdentityRolesPatchRequestBody struct {
	Patches []IdentityRolesPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Resource defines model for Resource.
type Resource struct {
	Entity Entity    `json:"entity"`
	Id     string    `json:"id"`
	Name   string    `json:"name"`
	Parent *Resource `json:"parent,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	Data []Resource `json:"data"`
}

// Response defines model for Response.
type Response struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// ResponseLinks defines model for ResponseLinks.
type ResponseLinks struct {
	Next ResponseLinksNext `json:"next"`
}

// ResponseLinksNext defines model for ResponseLinksNext.
type ResponseLinksNext struct {
	Href string `json:"href"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Page      *int    `json:"page,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	Size      int     `json:"size"`
	Total     *int    `json:"total,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Entitlements *[]RoleEntitlement `json:"entitlements,omitempty" validate:"omitempty,dive"`
	Id           *string            `json:"id,omitempty"`
	Name         string             `json:"name" validate:"required"`
}

// RoleEntitlement defines model for RoleEntitlement.
type RoleEntitlement struct {
	Entitlement *string `json:"entitlement,omitempty"`
	Entity      *Entity `json:"entity,omitempty"`
	Resource    *string `json:"resource,omitempty"`
}

// RoleEntitlementsPatchItem defines model for RoleEntitlementsPatchItem.
type RoleEntitlementsPatchItem struct {
	Entitlement EntityEntitlement           `json:"entitlement"`
	Op          RoleEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// RoleEntitlementsPatchItemOp defines model for RoleEntitlementsPatchItem.Op.
type RoleEntitlementsPatchItemOp string

// RoleEntitlementsPatchRequestBody defines model for RoleEntitlementsPatchRequestBody.
type RoleEntitlementsPatchRequestBody struct {
	Patches []RoleEntitlementsPatchItem `json:"patches" validate:"required,gt=0,dive"`
}

// Roles defines model for Roles.
type Roles struct {
	Data []Role `json:"data"`
}

// FilterParam defines model for FilterParam.
type FilterParam = string

// PaginationNextToken defines model for PaginationNextToken.
type PaginationNextToken = string

// PaginationNextTokenHeader defines model for PaginationNextTokenHeader.
type PaginationNextTokenHeader = string

// PaginationPage defines model for PaginationPage.
type PaginationPage = int

// PaginationSize defines model for PaginationSize.
type PaginationSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Response

// NotFound defines model for NotFound.
type NotFound = Response

// Unauthorized defines model for Unauthorized.
type Unauthorized = Response

// Default defines model for default.
type Default = Response

// GetIdentityProvidersParams defines parameters for GetIdentityProviders.
type GetIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetAvailableIdentityProvidersParams defines parameters for GetAvailableIdentityProviders.
type GetAvailableIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetEntitlementsParams defines parameters for GetEntitlements.
type GetEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsParams defines parameters for GetGroups.
type GetGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemEntitlementsParams defines parameters for GetGroupsItemEntitlements.
type GetGroupsItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemIdentitiesParams defines parameters for GetGroupsItemIdentities.
type GetGroupsItemIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemRolesParams defines parameters for GetGroupsItemRoles.
type GetGroupsItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesParams defines parameters for GetIdentities.
type GetIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemEntitlementsParams defines parameters for GetIdentitiesItemEntitlements.
type GetIdentitiesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemGroupsParams defines parameters for GetIdentitiesItemGroups.
type GetIdentitiesItemGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemRolesParams defines parameters for GetIdentitiesItemRoles.
type GetIdentitiesItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetResourcesParams defines parameters for GetResources.
type GetResourcesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken  *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	EntityType *string              `form:"entityType,omitempty" json:"entityType,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesItemEntitlementsParams defines parameters for GetRolesItemEntitlements.
type GetRolesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// PostIdentityProvidersJSONRequestBody defines body for PostIdentityProviders for application/json ContentType.
type PostIdentityProvidersJSONRequestBody = IdentityProvider

// PutIdentityProvidersItemJSONRequestBody defines body for PutIdentityProvidersItem for application/json ContentType.
type PutIdentityProvidersItemJSONRequestBody = IdentityProvider

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody = Group

// PutGroupsItemJSONRequestBody defines body for PutGroupsItem for application/json ContentType.
type PutGroupsItemJSONRequestBody = Group

// PatchGroupsItemEntitlementsJSONRequestBody defines body for PatchGroupsItemEntitlements for application/json ContentType.
type PatchGroupsItemEntitlementsJSONRequestBody = GroupEntitlementsPatchRequestBody

// PatchGroupsItemIdentitiesJSONRequestBody defines body for PatchGroupsItemIdentities for application/json ContentType.
type PatchGroupsItemIdentitiesJSONRequestBody = GroupIdentitiesPatchRequestBody

// PatchGroupsItemRolesJSONRequestBody defines body for PatchGroupsItemRoles for application/json ContentType.
type PatchGroupsItemRolesJSONRequestBody = GroupRolesPatchRequestBody

// PostIdentitiesJSONRequestBody defines body for PostIdentities for application/json ContentType.
type PostIdentitiesJSONRequestBody = Identity

// PutIdentitiesItemJSONRequestBody defines body for PutIdentitiesItem for application/json ContentType.
type PutIdentitiesItemJSONRequestBody = Identity

// PatchIdentitiesItemEntitlementsJSONRequestBody defines body for PatchIdentitiesItemEntitlements for application/json ContentType.
type PatchIdentitiesItemEntitlementsJSONRequestBody = IdentityEntitlementsPatchRequestBody

// PatchIdentitiesItemGroupsJSONRequestBody defines body for PatchIdentitiesItemGroups for application/json ContentType.
type PatchIdentitiesItemGroupsJSONRequestBody = IdentityGroupsPatchRequestBody

// PatchIdentitiesItemRolesJSONRequestBody defines body for PatchIdentitiesItemRoles for application/json ContentType.
type PatchIdentitiesItemRolesJSONRequestBody = IdentityRolesPatchRequestBody

// PostRolesJSONRequestBody defines body for PostRoles for application/json ContentType.
type PostRolesJSONRequestBody = Role

// PutRolesItemJSONRequestBody defines body for PutRolesItem for application/json ContentType.
type PutRolesItemJSONRequestBody = Role

// PatchRolesItemEntitlementsJSONRequestBody defines body for PatchRolesItemEntitlements for application/json ContentType.
type PatchRolesItemEntitlementsJSONRequestBody = RoleEntitlementsPatchRequestBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW2/bOPb/KoT+/6dCidOd7kuAATbTdtrMdpIgTbEPnaCgpWObE4nUkFQST+HvviAp",
	"6krJ8rXeWC+JbfFyePg7Fx4eUt+9gMUJo0Cl8M6/ewnmOAYJXH/7lUQS+I36TX0NQQScJJIw6p17F0hI",
	"TugUSYYmuiDiINJICjSee75HVKG/UuDqC8UxeOeeKef5nghmEGPVqJwn6olpy1ssfO8GTwnFqpcreJZ3",
	"7AFos/e7GaCAUUloqosiqcopWjhITuARkJwBovAskQCJ2MRS10IazftambqPgEPgu6BxZlrOiVRdntzg",
	"KZysRqqq4qaPQ8B4iNhkoigwpKWc5lM54Sxu4ViiGi1TEBNK4jT2zl/7lhpCJUyB18j5TP5uIYem8Ri4",
	"4YQiTJRISgzCEkYFtJAkVMMVkvBzRtLZmd9N4ML3bOsa/L/g8Bb+SkFI9U3NI1D9ESdJRAI9kNGfgmlw",
	"wjOOk0gP6ltE6INuQU2s+j/jMPHOPc2EbzFIbCRNTcmZb2hWHySTOPLOzxa+F2JV6Ou978UghC6p6EE8",
	"I8j3hMQyFd75mzNVvhjw/5u+/m9UyPXIPBWjW8s8Pdgq81XrdrgL37ti8leW0vAwhn7FJJpocsoDf7OV",
	"gRdtL3zvC8WpnDFO/oYDGXqFovLoX29l9JXm9dMJTiN5KGOH5wQCCSECzhkvjf+fW4J9o4tF3qwe0MUj",
	"JhEeR3AZApVEzm84eySZtk84S4BLYvQFCR1a2Goml3pWwky4AtpXVfk+10ls/CcEWgxbuxfN/g0Hv3tE",
	"QiyW8aR9XIucDMw5njco1d24aH2LEzwmEbH0ZAAR3vlXS9zX7x7QMGFEwcobEdO3Kq+mXc5YqEp7H97f",
	"efeL+8W9v8kQc3rmWxjTvMnvYiSOWc9HUyIWqDI9Zni+d3P9Wf/7ov6+e//p/d179fXi7u3HEilFi50D",
	"yGkpenYN572e6sbkKOR6aUqUgsnqKOHnLIoUIBrT4EK67z2fMJyQk4CFMAV6As+S4xOJp7rKI45IiKWq",
	"kNO9yEe1lcZqLNEt+m2CZTih/0YQZ2quPr/5w29bJNM3Dc+/uRXDZm3ujp3lDqpD8Juc6sXxSwlxJ9eX",
	"CXhzDp1EZ89cNH0A2a5hc7OhDGAUXU+0rPQzNP6a2ld4i3tDV1mb7pCSitK2fZdYumnfG+hvx/Sup8az",
	"UX3gLE1e8NAuc2u6Q7wUnVQ7v2XRTvvV7Ve73GV3poO8vx/FWqseXiZq7eh+0GzuRdO3K3j7ZL+ScwuC",
	"pTzYbY+2j6JXFsHLxPA+Z0+heMNl5zY8Qd2y05uqG9gbLIOZdfP6McbtJTYnnSXlFRUO1dKFQ8weobl4",
	"Wn3QPqPAJj/jMERZow0usKQNFE4uZKG1X1joWEkmqgSI3iDuYPRCBzkvTSuva9BegxFT+fOZHxIXByzV",
	"rVAoDFoFCHX4Qr4o3cpK6IcjIx+R7waJmzvbB4iL/YcED63aOpCx/4n0Pc6iHWlN3XI3IgqGbB8MNWYf",
	"Eg42DWUau7h2iK/kdm9Gh3XoNibFMec4DCH8pR6589hDpaXNFGegupuQQD9yeBQQYxJtTU1PCBfyyh0b",
	"971pDoz6Np3f5vD8yQgF96MIC/mJTQltfdpKSAI8JkIQRluo4dpBcz4yXnB9zuBZAqc40juY2cftTGE9",
	"+KXnKyfDz0HUBb2jd99aGbFVndzN7gPRztX1eYelntqVyctw4MxwWm21gy07wUad7QeGivaNUBwEkEhx",
	"w1mcyCtGy5p1zFgEmKqGcBCwlMpPhD4QOr2m0dxdLoiIUiTvnPrZPPwMAQf3RlxIRDnQfkknzN0NUFUu",
	"dD9ssTnW1X+rBuI2ArTNsnAICYdAfuGR87mQjIPO8hFumkoFbgGHivqWgnMa/M5CKIsViRPG5SYCxWKF",
	"5kTOM4nKWtSbejwV8n3NXcgJWvQA1bZ8sc13tSthumG10sKTnSjAw1yz2Ohmy9blvF8EskOpWI1Rdhrx",
	"kxhBevIEQjqTAxLMe2yY5qQ7sk+yfu3WbufQN5XOgo51pbIcca0SUuQi9Ym/ftKFy0lKfWr9rsouSplK",
	"TvVtEpW+uzIhy2PMCloSfDuCovkuBnyyo61yweZh9ebBlarQiPSqH5f2fpX1VaXAZIAtS3vSpbp6+N3m",
	"jtU0SoXrJXOrnuQZw81JyfJOm/WyTLTls6VacBKc6eLWbIb++q+2W9KQknVsdKbn/APaLqgPc1kqSDMg",
	"saK+5SXN3YTlMvqOcznsZMJWrX07mw/F4NsIzyYWT2mHNa2dltps2RIwKnGgxSELx3lR+gCnTyAimJ/M",
	"WBTB/F8BpoySAEengU7ez5LjP6UPgP5jSn7UJb1GPuzdDNCERRF7InSKRAKBCQkSRhFLZUQoCH1o4eLm",
	"Elni0YRx/eOvHy4QDmNCiZDcVJpwnUYcIsmQjnfhQKInImcIU3SdAFV1CBUS0wCQnHGWTmcIo4SzMA2k",
	"UB2dorsZEYgIVQceWfTYJA4LxGESmVReQjU5j8CFemYOFZz+QT3f00Dzzr23lkc5ERdVwm8MAegtixMs",
	"ickCVdR4vpc17J17Z6dnp6/PPB22AIoT4p17P52+Pj3zlC2SM42MEU7lTGkrQ6sOmZjlap35RCCbyoki",
	"IqRAOIpQtjRVPDGrIzMUhUbd4GXonTsTGzQRxYGeFm1VFBnVjmi07U47a+gzJivVKI73rFctO3ezuK+d",
	"3PjH2VmPBPZ+yeOd+SKOhPLrfyswvDEUuBrOKR2VDpjoKq+XV6mn6785e7O8Un6Wo5rf313JFtT58Gkc",
	"Yz5XKoQIiQJGJ2SaKsGvArsEUCVpWhV/9WrgV1YlYcIB/7e2XYQRhae2xk8b0L9hwol9XrVTW8FDM7JQ",
	"VeOSp7DYIR7d/R8TBleASSsEF35dKY+Scuiph3oWM5ZGoT2bhrW6Rmxi+xfogbInfdhPmSIxFxJiX1vK",
	"bGGPrh8k9tEHxqYR+OgDkR/TMQIZnP6Rnp39FIw5GulP8Ad99eru+t31q1fn6AR91nZvrpvNelceg9sk",
	"dGQaD7ZhC7ahR/r40QnorQalcROtVIg0SRjXvlnGqJ7GwiGp30m4MNIZgXScI73VixzlK7aohtyC6Z+b",
	"9uSdbrgxo3pR4obTcU3vyuztcAWcmvYDSISRIHQaQX83wOWqdczZYI63Aoe+c9XlDlbtkD7YrRZPxdKV",
	"hF7dyeo6+n7ve0nqwNWXJMRyE81wk3ZAbHA2Xx6610BMpykLaodkeziaTySK0BhQKiBEY+P3laMqoZKc",
	"mFBATzMSzNCXSwRZLM06qWPIYwhFhCXGSULo9BRdRBHC1o/J+y1XVlYcQjQD5XRHjE5NBEdRUlTMDp46",
	"9XLlmNluPTLnwbkW3C51WwpmEOWyK6baSSAmNFWa8Mrcmumux/9bphtQfcj5RRfatzcYsM7+DNBvn6+v",
	"UCYZwgAyZiFETuaXo6tH4vUvr1y+2mbXiwTn0ZejdBSqslVwBRFqMD1hPMayLFUVEWpK1Yjjp07JkvAs",
	"R0mEyTKZ4vipt0jd4qeaVC3BT0FFFTl1z2XARIEJLPScKNYtAUSRLty+nIgiZIo5JzTLRB+04/61Y+34",
	"53EuoCrotEjPYN0RMeegvVMdB9Wl3cHxHN27WKRk5y/2uzIpdXpUsW/nhDfwUujE3sGyNviYWJgB0BAA",
	"qwTAOiagT1yrheG5Rtx16OpIRcg9By6Vu++oVKsGT+uIGJT4S4gp9Vfg/eIIenPeHCqoOtLKw9atoRkW",
	"SzTOEQYL9uHfDiGA+UoI3Zc+xjKYOa42DkPEeJYtibCbZDaacBZ3qG3VdqtgrabEi7MA+izwBQ2NE6KB",
	"mLP3gua5BWyCxswk2eEwRJja3E+UE+n53iOOUqgkbX5tpN02r8Er/3SifjrBtSvhsiLzE/Wt/LTcwNzW",
	"zc786bxXJclrEDDuJGDcScA4J8Bmx94vFr0vF11+3ceiebXwETrNa4rUUstIKsf3W71upWCKoko8cC8H",
	"/LJ8RelgDLdjDB3XqR1t5LMVlIdkAUtErmr2KgJ0uEavuIYo/6jtVsUwuQqNvU2NR8dFQP3XY8drSrqx",
	"udR+5Pd3dJoOXaq/1TBHRgaDsS2DUb1l72hthQuFh7VQUhTmYpgv6pYaCSsvh2sfcjtgT93rf3rx8r2i",
	"/6vPx2vYA/ep+sEU9FlVtOPPaQh6Lh7s7nRRvCv59HjWCoe1jzysKrrQavFfgnz7vvKF1o55qn7niat1",
	"PPvVsk9/VNbr8cHHMe9O3FR15woHMtoRVTlzQWDYa64ftlg6KX32nNv5X1Gg+zo1ceS7zz2m9AccjejQ",
	"+qkLI4Pif0nHHNbR/StsTzd2/fLjgG1b01XEDdvTu7rdYNihnvcG6T6VdZ/AS4ngIgjaqcn1JTtdkjXs",
	"T7+M/ele9xkPW9TzdWSqt31ccj5BKx1TpqpuiEAYxZC9ErmHeTyqYwx7MozHfj5hBXQeml2skGuFuO0U",
	"kMMmrnluYp/WMLt73fxvbllXH2+0Wb3k3vPBhsxXxV9v+9G9Sa0F1OwNYiHIlEJorx1aId4z7Flv3XIc",
	"+bZ1T1z+TxgNPYxeNmPYy267xX2wFmtYixx4rcaCl29l78xisjuDxZ0deV33Kfe85aPZz9Zq5q8U+LzQ",
	"M2ZG7sybzwvwO64amCeQn2JXU4gmev8bjeee79JHuzRCzTe9Hv3tAi24t5JVCFImWL1SA23jLRbCviN2",
	"SAn5ASkhQ96gG6I54jUye94voAq7M0HWc3n6zaK5OX2/+4BFn0d7t4Cd7DpScr24NOnDJHRkOXlt+R4a",
	"OUOqh+Z/g2FNKV2e4OFmtlWFu87rOE7BcU6AQ8Xu/T6BFo2d1sAwKO0XcJdAP4XdL1PD+g2VfXB97GC5",
	"ehkSNHbhxA7JGfNeuNyT1t3GrQEtylkHylqEacjJeBk5GUtfqjVER+dry5PLAIonPJ0CP7Wi0ePWZV66",
	"Dbh89+91AvTi5lK/fcrPblwO7D3J+ormCeMohHE6nRI69dGYsyehP6lqIREBewQ+9/WbPhry/9lQ+pvQ",
	"sraRWel1tWjrDcjlcSIsEM7uZyVVLut3VmbYB/5o1Wy1oyTCAcxYpKyl76U88s69mZSJOB+NSs9OAxaP",
	"Hl9rg5q131CxtJghffW1ejg2ofPy9ctKl2VvKSsUfeV+ZqU0HNuoOIrqN31n91oX0cOixdoV3802L1DA",
	"oggC8/608pmcsv3Jf1vewNRmJGSVs+/LK/IsRpPVM1+XV4OqBSorSvtrj75L+wi2//ynxf3ivwEAAP//",
	"DjP1koWgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
